update INSTALL

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -148,21 +148,28 @@ if [ $mb == 'b' ]; then
     echo "* * * * * snoplusmon flock -n /tmp/rsync.lck rsync -av $host:/var/log/snoplus/ /var/log/snoplus" > $temp
     sudo cp $temp /etc/cron.d/rsync
 
-    while true; do
-        read -p "Set up SSH key now (y/n)? " yn
-        case $yn in
-            [Yy]*)
-                # set up password less SSH login for rsync
-                set +e
-                sudo -u snoplusmon -H bash -c "ssh-keygen"
-                sudo -u snoplusmon -H bash -c "ssh-copy-id $host"
-                set -e;;
-            [Nn]*)
-                break;;
-            *)
-                echo "Please answer yes or no.";;
-        esac
-    done
+    sudo -u snoplusmon -H bash -c "ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=0 $host echo hello"
+
+    if [ $? -ne 0 ]; then
+        # previous command failed
+        echo "password-less SSH is not set up."
+        while true; do
+            read -p "Set up SSH key now (y/n)? " yn
+            case $yn in
+                [Yy]*)
+                    # set up password less SSH login for rsync
+                    set +e
+                    sudo -u snoplusmon -H bash -c "ssh-keygen"
+                    sudo -u snoplusmon -H bash -c "ssh-copy-id $host"
+                    set -e
+                    break;;
+                [Nn]*)
+                    break;;
+                *)
+                    echo "Please answer yes or no.";;
+            esac
+        done
+    fi
 fi
 
 # make sure nginx user exists
