add master/backup install options

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -5,6 +5,34 @@ if ! hash git 2>/dev/null; then echo "Please install git."; fi
 if ! hash virtualenv 2>/dev/null; then echo "Please install virtualenv."; fi
 if ! hash gcc 2>/dev/null; then echo "Please install gcc."; fi
 
+if [ -f /etc/debian_version ]; then
+    supervisord_init=supervisord_debian
+    nginx_init=nginx_debian
+elif [ -f /etc/redhat-release ]; then
+    supervisord_init=supervisord_redhat
+    nginx_init=nginx_redhat
+else
+    echo "Error! Couldn't determine Linux distribution!"
+    echo "no /etc/debian_version or /etc/redhat-release file"
+    exit 1
+fi
+
+while true; do
+    read -p "Install master or backup [m/b]? " mb
+    case $mb in
+        [Mm]* )
+            redis_conf=redis.conf;
+            supervisord_conf=supervisord.conf;
+            nginx_conf=nginx.conf;
+            break;;
+        [Bb]* )
+            redis_conf=redis_backup.conf;
+            nginx_conf=nginx_backup.conf;
+            break;;
+        *) echo "Please answer m or b.";;
+    esac
+done
+
 add_service () {
     # adds an init script service to chkconfig or update-rc.d
     if [ -f /etc/debian_version ]; then
@@ -104,7 +132,7 @@ fi
 # make sure snoplusmon user exists
 if ! id -u snoplusmon >/dev/null; then
     echo "Adding snoplusmon user..."
-    sudo useradd -r snoplusmon
+    sudo useradd snoplusmon
 fi
 
 # make sure nginx user exists
@@ -125,33 +153,17 @@ sudo cp init/gunicorn /etc/init.d/gunicorn
 # add gunicorn service
 add_service gunicorn
 
-if [ -f /etc/debian_version ]; then
-    sudo cp init/supervisord_debian /etc/init.d/supervisord
-elif [ -f /etc/redhat-release ]; then
-    sudo cp init/supervisord_redhat /etc/init.d/supervisord
-else
-    echo "Error! Couldn't determine Linux distribution!"
-    echo "no /etc/debian_version or /etc/redhat-release file"
-    exit 1
+if [[ ! -z "$supervisord_conf" ]]; then
+    # only install supervisord init if this is installed
+    # as master
+    sudo cp init/$supervisord_init /etc/init.d/supervisord
+    add_service supervisord
+    sudo cp etc/$supervisord_conf /etc/supervisord.conf
 fi
 
-add_service supervisord
-
-sudo cp etc/supervisord.conf /etc/supervisord.conf
-
-if [ -f /etc/debian_version ]; then
-    sudo cp init/nginx_debian /etc/init.d/nginx
-elif [ -f /etc/redhat-release ]; then
-    sudo cp init/nginx_redhat /etc/init.d/nginx
-else
-    echo "Error! Couldn't determine Linux distribution!"
-    echo "no /etc/debian_version or /etc/redhat-release file"
-    exit 1
-fi
-
+sudo cp init/$nginx_init /etc/init.d/nginx
 add_service nginx
-
-sudo cp etc/nginx.conf /etc/nginx/nginx.conf
+sudo cp etc/$nginx_conf /etc/nginx/nginx.conf
 
 sudo mkdir -p /var/log/nginx
 sudo chown -R nginx:nginx /var/log/nginx
@@ -161,7 +173,7 @@ sudo cp init/redis_6379 /etc/init.d/redis_6379
 
 # redis configuration file
 # this is where, for example, the location of the backup image is configured
-sudo cp etc/redis.conf /etc/redis/6379.conf
+sudo cp etc/$redis_conf /etc/redis/6379.conf
 
 # add redis service
 add_service redis_6379
@@ -171,4 +183,6 @@ set -x
 
 sudo /etc/init.d/nginx restart
 sudo /etc/init.d/gunicorn restart
-sudo /etc/init.d/supervisord restart
+if [[ ! -z "$supervisord_conf" ]]; then
+    sudo /etc/init.d/supervisord restart
+fi
