update INSTALL with package dependencies

diff --git a/INSTALL b/INSTALL
--- a/INSTALL
+++ b/INSTALL
@@ -1,5 +1,31 @@
 set -e; sudo -v || exit
 
+# apt-get install package dependencies
+if [ -f /etc/debian_version]; then
+   sudo apt-get install git dpkg-dev make g++ gcc binutils libx11-dev libxpm-dev \
+       libxft-dev libxext-dev \
+       gfortran libssl-dev libpcre3-dev \
+       xlibmesa-glu-dev libglew1.5-dev libftgl-dev \
+       libmysqlclient-dev libfftw3-dev cfitsio-dev \
+       graphviz-dev libavahi-compat-libdnssd-dev \
+       libldap2-dev python-dev libxml2-dev libkrb5-dev \
+       libgsl0-dev libqt4-dev \
+       curl libcurl3 bzip2 libbz2-1.0 scons
+elif [ -f /etc/redhat-release ]; then
+   sudo yum install git make gcc-c++ gcc binutils \
+       libX11-devel libXpm-devel libXft-devel libXext-devel \
+       gcc-gfortran openssl-devel pcre-devel \
+       mesa-libGL-devel glew-devel ftgl-devel mysql-devel \
+       fftw-devel cfitsio-devel graphviz-devel \
+       avahi-compat-libdns_sd-devel libldap-dev python-devel \
+       libxml2-devel gsl-static \
+       curl curl-devel bzip2 bzip2-devel scons
+else
+    echo "Error! Couldn't determine Linux distribution!"
+    echo "no /etc/debian_version or /etc/redhat-release file"
+    exit 1
+fi
+
 add_service () {
     if [ -f /etc/debian_version ]; then
         sudo update-rc.d $1 defaults
